name: test-build-deploy
run-name: Test, Build and Deploy app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      
      - name: Checkout canonical/chisel
        uses: actions/checkout@v3
        with:
          repository: canonical/chisel
          path: chisel-repo

      - name: Build canonical/chisel
        run: |
          cd $GITHUB_WORKSPACE/chisel-repo/cmd && ./mkversion.sh
          cd $GITHUB_WORKSPACE/chisel-repo && go build -o $(pwd) $(pwd)/cmd/chisel && mv chisel $GITHUB_WORKSPACE

      - name: Build systemd container
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p container/opt
          chisel cut --root container ca-certificates_data libstdc++6_libs
          ls container

