name: test-build-deploy
run-name: Test, Build and Deploy app
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
